const dummyCardList = [
  {
    id: 1,
    imgSrc: "/src/assets/images/image.png",
    imgAlt: "Stir Fried Noodles",
    title: "Stir Fried Noodles",
    description:
      "A quick and tasty stir-fried noodle recipe packed with veggies and savory sauce.",
    ingredients: [
      "Egg noodles",
      "Soy sauce",
      "Garlic cloves",
      "Carrots",
      "Bell peppers",
      "Sesame oil",
      "Green onions",
    ],
    steps: [
      "Cook the egg noodles according to package instructions.",
      "Stir-fry garlic, carrots, and bell peppers in sesame oil.",
      "Add cooked noodles and soy sauce, tossing until combined.",
      "Garnish with green onions and serve.",
    ],
  },
  {
    id: 2,
    imgSrc: "/src/assets/images/eggplant.jpg",
    imgAlt: "Seared Eggplant",
    title: "Seared Eggplant",
    description:
      "This seared eggplant dish is perfect for a light and flavorful vegetarian meal.",
    ingredients: [
      "Eggplant",
      "Olive oil",
      "Garlic cloves",
      "Lemon juice",
      "Salt",
      "Pepper",
      "Parsley",
    ],
    steps: [
      "Slice eggplant and season with salt and pepper.",
      "Sear in olive oil until golden and soft.",
      "Drizzle with lemon juice and garnish with parsley before serving.",
    ],
  },
  {
    id: 3,
    imgSrc: "/src/assets/images/carrotmuffin.jpg",
    imgAlt: "Carrot Muffins",
    title: "Savoury Muffin",
    description:
      "Delicious savory muffins made with carrots and a blend of spices.",
    ingredients: [
      "Grated carrots",
      "Whole wheat flour",
      "Eggs",
      "Milk",
      "Baking powder",
      "Cheddar cheese",
      "Paprika",
    ],
    steps: [
      "Preheat oven to 180°C and line a muffin tray.",
      "Mix grated carrots, flour, eggs, milk, baking powder, and paprika.",
      "Fold in cheddar cheese and pour the mixture into the muffin tray.",
      "Bake for 20 minutes until golden.",
    ],
  },
  {
    id: 4,
    imgSrc: "/src/assets/images/djonmustardsalmon.jpg",
    imgAlt: "Dijon Mustard Salmon",
    title: "Dijon Mustard Salmon",
    description:
      "A simple yet flavorful Dijon mustard salmon baked to perfection.",
    ingredients: [
      "Salmon fillets",
      "Dijon mustard",
      "Honey",
      "Garlic cloves",
      "Lemon juice",
      "Salt",
      "Pepper",
    ],
    steps: [
      "Preheat oven to 200°C.",
      "Whisk Dijon mustard, honey, garlic, and lemon juice together.",
      "Brush the salmon fillets with the mustard mixture and season with salt and pepper.",
      "Bake for 12-15 minutes until salmon is cooked through.",
    ],
  },
  {
    id: 5,
    imgSrc: "/src/assets/images/ricenoodles.jpg",
    imgAlt: "Rice Noodles",
    title: "Rice Noodles with Vegetables",
    description:
      "A light and refreshing rice noodle dish with sautéed vegetables.",
    ingredients: [
      "Rice noodles",
      "Soy sauce",
      "Carrots",
      "Zucchini",
      "Garlic cloves",
      "Sesame oil",
    ],
    steps: [
      "Cook rice noodles according to package instructions.",
      "Stir-fry garlic, carrots, and zucchini in sesame oil.",
      "Add the cooked noodles and soy sauce, toss well, and serve.",
    ],
  },
  {
    id: 6,
    imgSrc: "/src/assets/images/garlicpotatoes.jpg",
    imgAlt: "Garlic Potatoes",
    title: "Garlic Roasted Potatoes",
    description:
      "Crispy roasted potatoes with a delicious garlic and herb seasoning.",
    ingredients: [
      "Potatoes",
      "Garlic cloves",
      "Olive oil",
      "Rosemary",
      "Salt",
      "Pepper",
    ],
    steps: [
      "Preheat oven to 200°C.",
      "Toss potato wedges with olive oil, garlic, rosemary, salt, and pepper.",
      "Roast for 30-35 minutes until crispy and golden.",
    ],
  },
  {
    id: 7,
    imgSrc: "/src/assets/images/Meatloafburger.jpg",
    imgAlt: "Meatloaf Burger",
    title: "Meatloaf Burger",
    description:
      "A hearty meatloaf patty served in a burger bun with your favorite toppings.",
    ingredients: [
      "Ground beef",
      "Onion",
      "Breadcrumbs",
      "Ketchup",
      "Egg",
      "Burger buns",
      "Lettuce",
      "Cheese",
    ],
    steps: [
      "Mix ground beef, chopped onion, breadcrumbs, ketchup, and egg.",
      "Form into patties and cook on a skillet until browned.",
      "Serve in a bun with lettuce, cheese, and additional toppings of choice.",
    ],
  },
  {
    id: 8,
    imgSrc: "/src/assets/images/Sloppy-Joes.jpg",
    imgAlt: "Sloppy Joes",
    title: "Sloppy Joes",
    description:
      "A tangy and delicious sloppy joes sandwich made with seasoned ground beef.",
    ingredients: [
      "Ground beef",
      "Onion",
      "Tomato sauce",
      "Worcestershire sauce",
      "Brown sugar",
      "Burger buns",
    ],
    steps: [
      "Cook ground beef and onions in a skillet until browned.",
      "Stir in tomato sauce, Worcestershire sauce, and brown sugar, simmer until thickened.",
      "Serve in a burger bun and enjoy.",
    ],
  },
  {
    id: 9,
    imgSrc: "/src/assets/images/smokedsalmonbowl.jpg",
    imgAlt: "Smoked Salmon Bowl",
    title: "Smoked Salmon Bowl",
    description:
      "A fresh and healthy smoked salmon bowl with rice, avocado, and pickled veggies.",
    ingredients: [
      "Smoked salmon",
      "Rice",
      "Avocado",
      "Pickled cucumber",
      "Soy sauce",
      "Sesame seeds",
    ],
    steps: [
      "Cook rice and divide into bowls.",
      "Top with smoked salmon, avocado, and pickled cucumber.",
      "Drizzle with soy sauce and sprinkle sesame seeds on top.",
    ],
  },
  {
    id: 10,
    imgSrc: "/src/assets/images/beefchilli.jpg",
    imgAlt: "Beef Chili",
    title: "Beef Chili",
    description:
      "A hearty beef chili made with beans, tomatoes, and a blend of spices.",
    ingredients: [
      "Ground beef",
      "Kidney beans",
      "Tomato sauce",
      "Chili powder",
      "Onions",
      "Garlic cloves",
    ],
    steps: [
      "Cook ground beef, onions, and garlic in a pot until browned.",
      "Add kidney beans, tomato sauce, and chili powder.",
      "Simmer for 30 minutes and serve hot.",
    ],
  },
  {
    id: 11,
    imgSrc: "/src/assets/images/image.png",
    imgAlt: "Basil Garlic Beef Stir-fry",
    title: "Basil Garlic Beef Stir-fry",
    description:
      "A fragrant stir-fry with ground beef, garlic, and fresh basil.",
    ingredients: [
      "Olive oil",
      "Garlic cloves",
      "Fresh basil",
      "Tomato paste",
      "Ground beef",
      "Parmesan cheese",
      "Button mushrooms",
      "Soy sauce",
      "Cumin powder",
      "Lemon zest",
    ],
    steps: [
      "Finely chop garlic, fresh basil, and slice button mushrooms, then mix soy sauce, cumin, and lemon zest in a bowl.",
      "Heat olive oil in a skillet over medium-high heat, then add ground beef and cook until browned.",
      "Add chopped garlic and sliced mushrooms to the skillet, sautéing until the mushrooms are tender and garlic is fragrant.",
      "Pour the soy sauce mixture over the beef and vegetables, stirring in the fresh basil for another minute.",
      "Remove from heat and serve hot, garnished with Parmesan cheese and additional basil, over rice or pasta.",
    ],
  },
];

export default dummyCardList;
